---
title: "Einstieg"
<<<<<<< HEAD
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
Woche <- c(1, 4, 52)
Gramm <- c(5,20,260)
Einstieg <- tibble(Woche, Gramm)

Einstieg %>%
  ggplot(aes(Woche, Gramm)) +
  geom_point(colour= "blue", size = 6) +
  scale_y_continuous(limits = c(0, 300)) +
  geom_smooth(method = "lm", colour= "grey") +
  labs(title = "Durchschnittliche Plastik-Aufnahme eines Menschen", subtitle = "Mikroplastik (in Gramm) pro Woche") +
    annotate(geom = "text", label= "Kreditkarte", x= 5.5, y= 4)+ 
    annotate(geom= "text", label= "fünf Bleistifte", x= 9, y= 23) +
    annotate(geom= "text", label= "Pckg. Butter", x= 51,y= 240) +
  theme_test() 
  ggsave(filename = "Einstiegsidee.png")
```

=======
author: "Caroline Kreiß"
date: "14 7 2021"
output: html_document
---

```{r}
library(tidyverse)
library(fs)
library(dplyr)
library(dplyr)
library(ggplot2)
```

```{r}
Woche <- c (1:52)
Gramm <- c(seq(5, 260, length.out = 52))

Einstieg <- tibble(Woche, Gramm)
```


#Einstiegsidee
```{r}
Einstieg %>%
  ggplot(aes(Woche, Gramm)) +
  geom_point(colour= "blue", size = 4) +
    scale_y_continuous(limits = c(0, 300)) +
    scale_x_continuous (limits = c(0,60), breaks= c(0, 1,4,25, 52, 60)) +
  geom_smooth(method = "lm", colour= "grey") +
  labs(title = "Durchschnittliche Aufnahme von Plastik pro Person", subtitle = "Mikroplastik (in Gramm) pro Woche entspricht...") +
   annotate(geom = "text", label= "Kreditkarte", x= 4.5, y= 4) + 
   annotate(geom= "text", label= "fünf Bleistifte", x= 7, y= 23) +
annotate(geom= "text", label= "Creme", x= 24, y= 120) +
   annotate(geom= "text", label= "Butter", x= 53,y= 240) +
    theme_test() 
  
  ggsave(filename = "Einstiegsidee.png")
```

```{r}
#Idee: geom_point und geom_line kombinieren 
Woche <- c(1, 4, 25, 52)
Gramm <- c(5,20,125,260)
Einstieg_HL <- tibble(Woche, Gramm)

Einstieg_HL %>%
  ggplot(aes(Woche, Gramm)) +
   geom_line () +
  geom_point(colour= "#00868B", size = 4) +
    scale_y_continuous(limits = c(0, 300)) +
    scale_x_continuous (limits = c(0,60), breaks= c(0, 1, 4, 25, 52, 60)) +
 #geom_smooth(method = "lm", colour= "grey") +
  labs(title = "Durchschnittliche Aufnahme von Plastik pro Person", subtitle = "Mikroplastik (in Gramm) pro Woche entspricht ungefähr...") +
   annotate(geom = "text", label= "Kreditkarte", x= 5.4, y= 2.5) + 
   annotate(geom= "text", label= "Zahnbürste", x= 9.2, y= 20) +
annotate(geom= "text", label= "Creme-Tube", x= 30, y= 120) +
   annotate(geom= "text", label= "Butter", x= 54.5,y= 250) +
    theme_test()

ggsave(filename = "Einstieg_Highlights.png")
EinstiegsPlot <- "Einstieg_Higlights.png"

butter <- system.file ("logos/butter.png", package = "cowplot")
kreditkarte <- system.file ("logos/kreditkarten.png",package = "cowplot")

EinstiegsPlot <- ggdraw () +
  draw_image ("logos/butter.png",  x = 0.3, y = 0.4, scale = .2) +
  draw_plot (EinstiegsPlot)
EinstiegsPlot
```

