---
title: "My Website"
description: |
  Welcome to the website. I hope you enjoy it!
site: distill::distill_website
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# Learn more about creating websites with Distill at:
# https://rstudio.github.io/distill/website.html
 
library(tidyverse)
library(ggplot2)
library(dbplyr)
```

```{r}
global_plastic_fate <- readr::read_csv("data/global-plastic-fate.csv")



global_plastic_fate %>%
group_by(Entity) %>%
ggplot(aes(x = Year, y = `Estimated historic plastic fate`, color= Entity)) + 
 geom_point()+
 scale_x_continuous(limits = c(1980, 2015), breaks = c(1980, 1990, 2000, 2010, 2015), expand = c(0.02,0.02))+
  labs(x= "", y= "prozentualer Anteil", title= "Globaler Kunststoffabfall differnziert nach Entsorgungsart, 1980 bis 2015")+
  scale_colour_discrete(name= "Entsorgungsart", breaks=c("Discarded", "Incinerated", "Recycled"),labels= c("Entsorgung (auf Mülldeponien)", "Verbrennung", "Recyceln"))+
  theme_minimal_hgrid(12)
 
 

```

